version: '3'
services:
    sweetiepull:
        build: .
        image: sweetiepull
        ports:
            - "${PORT}:3000"
    spredis:
        image: 'redis'
        volumes:
            - './data:/data'

